# Page settings

baseurl = "https://bezha.github.io/cv/"
languageCode = "en-us"
title = "Bezhanovych Vitalii Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
     description = "Bezhanovych Vitalii CV"
#    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Bezhanovych Vitalii"
        tagline = "Junior DevOps"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: bezhav@gmail.com"
        title = "bezhav@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:by request"
        title = "by request"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//bezha.od.ua"
        title = "bezha.od.ua"

        [[params.contact.list]]
        class = "CV"
        icon = "fa-globe"
        url = "//cv.bezha.od.ua"
        title = "cv.bezha.od.ua"

        [[params.contact.list]]
        class = "F.A.Q."
        icon = "fa-globe"
        url = "//bezha.github.io/faq/"
        title = "faq.bezha.od.ua"

        #[[params.contact.list]]
        #class = "linkedin"
        #icon = "fa-linkedin"
        #url = "//linkedin.com/in/johndoe"
        #title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/bezha"
        title = "github.com/bezha"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/bezha"
        title = "@bezha"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Computer Science"
        college = "Odessa National Maritime University (ONMU)"
        dates = "2001 - 2006"


    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Russian"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Intermediate"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Football"

        [[params.interests.list]]
        interest = "Cycling"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**A self-motivated, enthusiastic midlife career changer pursuing cloud engineer position.** Wants to change mind paradigm from on-premises to cloud way with AWS/Terraform/Kubernetes. Seeking Cloud Mentor."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = " DataCenter System Administrator"
        dates = "2012 - Present"
        company = "USA NY DataCenter"
        details = "**My current role:** Technical support for clients requests; Installing OS/Software to Dedicated/VPS; **Virtualization** with SolusVM: OpenVZ/KVM/XEN; **Monitoring** Hardware Nodes with: Nagios/Prometheus; **Backup** VPS; **Ansible**:Provisioning monitoring software; Sharing Hosting: Installing/Support: Cpanel/Plesk"
        [[params.jobs.list]]
        position = "DataCenter System Administrator"
        dates = "2007 - 2010"
        company = "Technologies of the Future LLC Hosting.UA"
        #details = "**Describe your role here**"


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = " My Projects"
        #intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Docker Megacli"
        url = "https://github.com/bezha/Docker-MegaCli"
        tagline = "Docker container for running MegaCli and SMART/IPMI scripts. GitHub Actions Workflow CI/CD to store image on https://hub.docker.com/"

        [[params.projects.list]]
        title = "Docker Megacli"
        url = "https://github.com/bezha/docker_megacli_on_ghcr.io"
        tagline = "Docker container for running MegaCli and SMART/IPMI scripts. GitHub Actions Workflow CI/CD to store image on https://ghcr.io/"

        [[params.projects.list]]
        title = "Hugo CV Github Pages"
        url = "https://github.com/bezha/hugo.cv.bezha.od.ua"
        tagline = "Hosting CV on Github Pages with Github Actions CI/CD https://bezha.github.io/cv/"

        [[params.projects.list]]
        title = "Hugo CV S3"
        url = "https://s3.eu-central-1.amazonaws.com/cv.bezha.od.ua/index.html"
        tagline = "Hosting CV on S3 with Github Actions CI/CD https://github.com/bezha/hugo.cv.bezha.od.ua"

        [[params.projects.list]]
        title = "AWS EKS CV"
        url = "https://github.com/bezha/EKS_Kubernetes_CV"
        tagline = "AWS EKS CV stateless application"

        [[params.projects.list]]
        title = "Prepairing to AWS Certifications Cloud Practitioner"
        url = "https://bezha.od.ua/aws-certifications-cloud-practitioner/"
        tagline = "AWS CCP"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Linux: CentOS/Ubuntu"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Monitoring:Nagios/Prom"
        level = "70%"

        [[params.skills.list]]
        skill = "Ansible"
        level = "50%"

        [[params.skills.list]]
        skill = "Docker"
        level = "15%"

        [[params.skills.list]]
        skill = "AWS"
        level = "2%"

        [[params.skills.list]]
        skill = "Kubernetes"
        level = "2%"

        [[params.skills.list]]
        skill = "Terraform"
        level = "2%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
